spring.datasource.url=jdbc:postgresql://localhost:5433/best_travel
spring.datasource.username=carlos
spring.datasource.password=830701
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-size=5

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE